runtime: nodejs20
service: default  # opcional

handlers:
  # ✅ Redirección global HTTP -> HTTPS (301)
  - url: /.*
    secure: always
    redirect_http_response_code: 301

  # Estáticos con caché largo (traen hash en el nombre)
  - url: /(.*\.(?:css|js|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|map))
    static_files: build/\1
    upload: build/.*\.(?:css|js|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|map)
    secure: always
    http_headers:
      Cache-Control: public, max-age=31536000, immutable

  # (Si existe) service worker: sin caché para que tome la última versión
  - url: /service-worker.js
    static_files: build/service-worker.js
    upload: build/service-worker.js
    secure: always
    http_headers:
      Cache-Control: no-cache

  # (Si existe) manifest: sin caché
  - url: /manifest.webmanifest
    static_files: build/manifest.webmanifest
    upload: build/manifest.webmanifest
    secure: always
    http_headers:
      Cache-Control: no-cache

  # SPA fallback: index.html sin caché
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    http_headers:
      Cache-Control: no-cache
