steps:
  - name: gcr.io/cloud-builders/npm
    args: ["install"]

  - name: gcr.io/cloud-builders/npm
    args: ["run", "build"]
    env:
      - 'REACT_APP_EMAILJS_SERVICE_ID=service_n63g82y'
      - 'REACT_APP_EMAILJS_TEMPLATE_ID=template_pnabaae'
      - 'REACT_APP_EMAILJS_PUBLIC_KEY=wz2btEynCC939gKaJ'

  - name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
      - app.yaml
      - --project=memos-tablet
      - --quiet

# Bucket de logs (si el trigger te obliga por el service_account)
logsBucket: 'gs://logs-sdlabs'

timeout: "600s"
